services:
  - type: web
    name: chainpostwhisper
    env: python
    runtime: python-3.10.13
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
